version: '3.8'
services:
  api:
    build: .
    container_name: mycyberclinics-api
    env_file: .env
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
      - redis
    command: npm run dev
    networks:
      - mycyberclinics-net

  mongo:
    image: mongo:latest
    container_name: mycyberclinics-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mycyberclinics-net

  redis:
    image: redis:7-alpine
    container_name: mycyberclinics-redis
    ports:
      - "6379:6379"
    networks:
      - mycyberclinics-net
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 2s
      retries: 5

volumes:
  mongo_data:
  redis_data:

networks:
  mycyberclinics-net:
    driver: bridge