version: '3.8'
services:
  api:
    build: .
    container_name: mycyberclinics-api
    env_file: .env
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    command: npm run dev
    networks:
      - mycyberclinics-net

  mongo:
    image: mongo:latest
    container_name: mycyberclinics-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mycyberclinics-net

volumes:
  mongo_data:

networks:
  mycyberclinics-net:
    driver: bridge