version: '3.8'
services:
  mongo:
    image: mongo:6
    container_name: mycyberclinics-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  backend:
    build: .
    container_name: mycyberclinics-backend
    env_file:
      - .env
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start
volumes:
  mongo-data: